thinkingmachines/unicef-ai4d-research-bank

.vscode/launch.json
=> chore:Create placeholder for catalog json dir

catalog/povmap-timor-leste-rollout-dataset.yml, catalog/povmap-timor-leste.yml
* Test adding/updating catalog items via an external forked repo
=> trial:Add/update poverty mapping items from external fork

.eslintrc.json, package.json, pnpm-lock.yaml, src/index.css, src/pages/CataloguePage.tsx
To test:
- run `pnpm install` again to install antd
- added antd for components
- added skeleton for filter components
- added no-non-null eslint exception
- removed ring color for tailwind as it conflicts with antdesign
Screenshot:
Will improve design later!
=> Add filters (UI only, no functionality)

src/api/index.ts, src/pages/CatalogueItemPage.tsx, src/pages/CataloguePage.tsx, src/types/CatalogueItem.type.ts
=> Integrate fetch with frontend catalogue

src/components/CatalogueItemCard.tsx, src/pages/CataloguePage.tsx
- styling of banner
- styling of filters section
- styling of results
=> Style catalogue page

catalog/povmap-philippines.yml
* Fix links to ph povmap model
=> fix: Update broken links to PH model catalog item

.github/workflows/validate.yml
=> chore:Rename gh validate-catalog job

.github/workflows/deploy.yml
* Update deploy to also validate catalog items
=> feat: Update deploy GH Action to add catalog item validation

catalog/povmap-timor-leste.yml
* fix povmap-timor-leste.yml catalog item errors (missing fields)
=> fix:Revert to valid catalog entry

src/components/CatalogueItemCard.tsx, src/components/Tag.tsx, src/pages/CatalogueItemPage.tsx, src/pages/CataloguePage.tsx, src/pages/LandingPage.tsx
- styling catalogue item page
- adding type to catalogue card in catalogue page
Screenshots:
=> Style catalogue item

src/components/CatalogueItemCard.tsx, src/pages/CatalogueItemPage.tsx
- Adding check if optional values are empty in the catalogue item page and replacing it with `-`
- Update label for date modified field
=> Handle null values in the UI

.eslintrc.json, src/App.tsx, src/context/CatalogueItemContext.tsx, src/pages/CataloguePage.tsx
First part of rewriting fetching logic to use with filters and search.
- creating a context that loads the catalogue items in App.tsx
- updating the catalogue page to use the context
=> Create context for catalogue items

README.md
Add a cypress test coverage badge in the readme. 
* view [e2e test results here](https://cloud.cypress.io/projects/ivvovd/runs)
=> chore:Add cypress test badge to readme

src/__tests__/App.tsx
* Make unittest pass without error messages by mocking fetch
=> fix:Mock fetch to return catalog item

src/api/index.ts, src/context/FilterContext.tsx, src/pages/CatalogueItemPage.tsx
* Replace fetchCatalogItem with CatalogItemContext to reduce api call. 
* Remove unneeded api calls
=> feat:Replace fetch item api call with catalog item context

src/context/CatalogueItemContext.tsx, src/context/FilterContext.tsx, src/pages/CataloguePage.tsx, src/types/SearchFilters.type.ts, src/utils/Filters.util.ts
- filtering catalogue items based on these filters
- changed `catalogueIds` type to string[] for easier transformation
=> Add filter functionality for country, org, and tags

.eslintrc.json, package.json, pnpm-lock.yaml, src/context/FilterContext.tsx, src/pages/CataloguePage.tsx, src/types/SearchFilters.type.ts, src/utils/Filters.util.ts
- create date created filter
- create date updated filter
I also added new packages needed for the ant design date components (`Dayjs`, `rc-picker`).
=> Add date filters functionality

pnpm-lock.yaml, src/App.tsx, src/components/SearchInput.tsx, src/context/FilterContext.tsx, src/context/SearchContext.tsx, src/index.css, src/pages/CataloguePage.tsx, src/pages/LandingPage.tsx, src/types/SearchFilters.type.ts, src/utils/Filters.util.ts
- search functionality
- integration with filters
- integration with landing page search
- updating labels for search suggestions
The styling of the search bar still needs work (right now, I'm having trouble with conflicting styles of Tailwind and Ant Design) so I'll address that in another PR.
=> Add search functionality

.eslintrc.json, package.json, pnpm-lock.yaml, src/App.tsx, src/components/CatalogueItemCard.tsx, src/components/SearchInput.tsx, src/context/FilterContext.tsx, src/pages/CataloguePage.tsx, src/setupTests.ts, src/utils/Filters.util.ts, src/utils/String.util.ts, tailwind.config.js
- styling enhancement for catalogue item card
- truncating description to two lines only
- filtering search suggestions to 10 only
- updating ant design theme
- fix formatting of text
Screenshots:
=> Catalogue page styling enhancements

catalog/airquality-thailand-model.yml, catalog/povmap-timor-leste.yml
* This PR is expected to fail validation as the skip hxl tag validation has been removed
=> try: Add a csv without skip tag validation and create a PR

src/components/CatalogueItemData.tsx
- Adding a section for the data columns field under the Data tab
I also commented in the Schema discussion [here](https://github.com/thinkingmachines/unicef-ai4d-research-bank/discussions/45#discussioncomment-5516245)
Screenshot:
=> Add data columns section under the data tab

src/components/CatalogueItemData.tsx
Video:
https://user-images.githubusercontent.com/26348221/229691664-078ee97b-63e2-4056-afd6-9af751e3384c.mov
=> Add data preview section under the data tab

src/context/FilterContext.tsx, src/pages/CatalogueItemPage.tsx, src/pages/CataloguePage.tsx, src/pages/LandingPage.tsx, src/types/CatalogueItem.type.ts, src/types/SearchFilters.type.ts, src/utils/Filters.util.ts
- Updating the `year-period` type to string to accommodate period
- Replacing the Date Created and Date Updated filters with Year filter
=> Year filter

src/components/CatalogueItemData.tsx, src/components/CopyLinkButton.tsx
- extracting the copy link button to a new component
- creating isCopied indicator when the copy link button is clicked
https://user-images.githubusercontent.com/26348221/231650006-d7e9d14a-2998-42dc-ab71-fcb1577c9546.mov
=> Add copied! indicator on copy link click

pull_request_template.md
=> chore: add pull request template

README.md, SETUP.md, pull_request_template.md
=> chore: update readme

cypress/e2e/contribution-page.spec.ts, cypress/e2e/dropdown-filter.spec.ts, cypress/e2e/filter.spec.ts, cypress/e2e/pagination.spec.ts, cypress/e2e/radio-filter.spec.ts, public/api/data/fixtures/catalog.json, src/components/CatalogueItemCard.tsx, src/components/CustomSelect.tsx, src/components/Footer.tsx, src/pages/CataloguePage.tsx
Add tests
Also modifies current fixture, adds an extra dummy element so pagination could be properly tested
Add a summary of the things that were changed
Add a numbered list of steps to make in order to verify that the feature is working. Ideally add a video of you
running the new features you have added. You can use a capturing tool like [ShareX](https://getsharex.com)
0. Run `pnpm build:test-env`
1. Run `test:e2e:headless` and assert that all tests pass
=> tests: footer, contribution page, catalogue page filters, pagination, modify fixtures

.github/workflows/deploy.yml
=> fix:Update deploy to use PAT

.github/workflows/deploy.yml
- update string interpolation in gh action
=>  Fix GH Deploy action

catalog/high-resolution-settlement-layer-philippines.yml
=> chore:Add a simple update to item

.github/workflows/deploy.yml
=> fix:Add missing char in deploy gh action

catalog/high-resolution-settlement-layer-philippines.yml
- test: test gh action for deploy
- expect to trigger a validate action on PR
- expect to trigger a deploy action on merge
=> test:Remove a tag from an item

catalog/high-resolution-settlement-layer-philippines.yml
- test: update of catalog item from contributor repo
=> chore: test updating catalog item from contributor branch

src/pages/CatalogueItemPage.tsx
This feature is pushed back due to the api needed not being available
Add a summary of the things that were changed
=> feat: remove citations

SETUP.md
- doc: Add instructions to gstorage api instructions
=> doc:Add gstorage api key instructions

src/components/CatalogueItemData.tsx
Fix extra text on page
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix:Remove extra xxxx in page

.github/workflows/deploy.yml, .github/workflows/forcevalidate.yml, .vscode/settings.json, package.json, scripts/transform_catalog.py, scripts/validate_catalog.py
- Add  a force validation option for catalog validation 
- Add an  optional manually triggered github action to trigger forced validation for all  catalog items (including link check validation). 
- Adds a delay to gdrive url access during forced validation as rate limiter.
- Add a delay to gdrive url access during merge catalog (catalog.json creation) and generation of image assets
- Fix bug on restore mtime during deploy
- Chore: fix vscode settings
=> Feat/add  force validation gh action

catalog/povmap-cambodia.yml, catalog/povmap-cross-country-model.yml, catalog/povmap-myanmar.yml, catalog/povmap-philippines.yml, catalog/povmap-timor-leste.yml
Remove duplicate `relative-wealth` tags
=> remove duplicate tags
