- .eslintrc.json
- src/App.tsx
- src/context/FilterContext.tsx
- src/pages/CataloguePage.tsx
- src/pages/LandingPage.tsx
- src/types/SearchFilters.type.ts
- src/utils/Filters.util.ts
- loading the filter options for country, organization, and tags. filter functionality will go on the next PR
- updating the schema of the filter options to this:
```
tags = [
{ label: string, value: string, catalogueIds: Set<string> },
{ label: string, value: string, catalogueIds: Set<string> },
]
```
In this example, the `label` and `value` will have the unique tag value while the `catalogueIds` is the list of ids that has that tag. I thought it's more flexible this way and easier to filter in the front-end. I was able to remove the transform function `makeLabels` also since this schema fit with the filter component data schema.
All unused functions / components will be cleaned up in another PR!
> Create initial filter context and get filter options

- .eslintrc.json
- catalog/airquality-thailand-model.yml
- catalog/povmap-philippines.yml
- catalog/povmap-timor-leste.yml
- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/components/CatalogueItemData.tsx
- src/components/CatalogueItemLinks.tsx
- src/components/CatalogueItemOverview.tsx
- src/pages/CatalogueItemPage.tsx
- src/utils/Filters.util.ts
- src/utils/String.util.ts
- updating the content to show tabs for overview, data, and related links
- updating yaml files to add links for research-paper, limitations, and training dataset
- icons using @ant-design/icons
- fix formatting of text
For the data tab, I separated the training dataset, raw dataset, and dataset. For training datasets and raw datasets, I added a copy link button that copies the link to clipboard. For dataset, I just listed down the link. Reason for this is because that for raw datasets, they can just copy the link and paste it in their viz tools. For datasets that are not raw, they still need to download the data.
Not entirely sure if that should be the case for training datasets? Should we remove the copy link button for them?
Videos: …
> Add styling to catalogue item page + new fields

- src/App.tsx
- src/components/SearchInput.tsx
- src/index.css
- src/pages/LandingPage.tsx
- updating ant design theme to fix search styling
- adding allowClear feature for search
- fixing bug on unfiltered items when a suggestion is clicked. (e.g. if I search for a model in the landing page and click on a search suggestion, then navigate to the catalogue page, it still shows me all items even i have entered a search input)
Screenshots:
> Fix search styling, add allowClear feature, and bug fix

- src/App.tsx
- src/components/SearchInput.tsx
- src/pages/CatalogueItemPage.tsx
- src/pages/CataloguePage.tsx
- src/pages/LandingPage.tsx
This PR fixes:
- When I go to the catalogue page and enter a search term, then clear it, and then navigate to the landing page, the search term is still showing there in the search bar.
- Search against all catalogue items rather than filtered ones.
- When clicking on a tag in the landing page and catalogue item page - the search input is not being cleared out.
- For search and filters in the landing page, reset all filters to start fresh. 
- If I click on the landing page and I click on an entry and go back to landing page, I still get search suggestions from all.
- Link color in catalogue item page is not the primary color.
> Fix misc search bugs

- catalog/airquality-thailand-model.yml
- src/pages/CataloguePage.tsx
- src/utils/Filters.util.ts
- updating the filter logic to accommodate multiple years (ex. of 'year-period' = 2020-2023)
- allow empty start or end years
- if startYear is filled and endYear is empty, the results will be filtered to items that start with the startYear
- if endYear is filled and startYear is empty, the results will be filtered to items that end with the endYear
Screenshots:
> Update year filter to allow empty start or end years

- src/App.tsx
- src/components/NotFound.tsx
- src/pages/CatalogueItemPage.tsx
This PR includes creating a 404 page to let the user know that the link doesn't exist rather than showing a blank page. The 404 page is being handled via react-router.
See issue https://github.com/thinkingmachines/unicef-ai4d-research-bank/issues/52
Screenshot:
> Create 404 page for nonexistent links

- src/App.tsx
- src/components/CustomRadio.tsx
- src/components/CustomSelect.tsx
- src/constants/index.ts
- src/css/CustomSelect.css
- src/css/Pagination.css
- src/pages/CataloguePage.tsx
- Dedicated CSS files were used to override the styles of some of the components
- The filtering mechanisms of both the toggle and dropdown filer are applied after the main filters i.e. the variable that holds the filtered values processed by the old filters are passed down into the new filters then passed into the ui components
https://github.com/thinkingmachines/unicef-ai4d-research-bank/assets/122899250/4ae15990-bcd9-4728-94ff-3225bde2eb79
0. For testing pagination, you may need to generate more dummy catalog entries. You can do so by cloning the `yaml` files in the `catalog` folder. Note that spaces and duplicate names are not allowed. Also use this opportunity to change their `year-period` entries, their names and their `card-type` values in order to test the newly added features. …
> feat: add Pagination, Toggle filter, and Dropdown filter

- src/components/CatalogueItemData.tsx
- src/components/CatalogueItemLinks.tsx
- src/components/CatalogueItemOverview.tsx
- src/components/CopyLinkButton.tsx
- src/components/FeaturedItemCard.tsx
- src/constants/index.ts
- src/constants/texts.ts
- src/pages/CatalogueItemPage.tsx
- src/types/CatalogueItem.type.ts
- all dummy data is in the `constants` folder
1. Assert that the all the visual enhancements mentioned above are present
2. Assert that the downloading of CSVs or GEOJSONS redirect to the dummy link
[Wireframe](https://www.figma.com/file/uKFcwlIWJuadonbCejcZcy/Unicef-Open-Source-Web-App?type=design&node-id=823-2&t=49JYGjpKXdbm9SX7-0)
https://github.com/thinkingmachines/unicef-ai4d-research-bank/assets/122899250/110e1708-2cb9-463b-95dc-e10c675b1684
> feat: various visual enhancements placeholder data download

- cypress/e2e/index.spec.ts
- cypress/e2e/landing-page.spec.ts
- src/pages/CataloguePage.tsx
- src/pages/LandingPage.tsx
- The eslint disable snippet `/* eslint-disable cypress/require-data-selectors */` is used since antd components make heavy use of class selections which are frowned upon by this linting rule
0. Make sure you have cypress installed
1. Run `pnpm merge-catalog`
2. Run `pnpm build`
3. Run `pnpm test:e2e:headless` to run all tests or `pnpm test:e2e` to run the tests via a GUI
4. Assert that all the tests pass
> tests: add landing page tests

- cypress.config.ts
- cypress/.eslintrc.js
- cypress/e2e/catalog-item.spec.ts
- cypress/e2e/catalog-page.spec.ts
- cypress/e2e/featured-dataset.spec.ts
- cypress/e2e/filter.spec.ts
- cypress/e2e/index.spec.ts
- cypress/e2e/landing-page.spec.ts
- cypress/e2e/searchbox.spec.ts
- src/components/CatalogueItemData.tsx
- src/components/FeaturedItemCard.tsx
- src/pages/CatalogueItemPage.tsx
- src/pages/CataloguePage.tsx
- some eslint cypress rules were silenced due to the nature of testing antd components
- actual `catalog.json` file is used as a fixture for tests
- `data-cy` attributes are added to various components / elements in order for easier targeting by the tests
on fixtures: might be a good idea to have a dedicated fixture per sprint, so the backend data to be worked per sprint is more consistent and reliable
generally added tests from  [here](https://github.com/thinkingmachines/unicef-ai4d-research-bank/wiki/Frontend-Test-Cases)
0. Make sure you have cypress installed
1. Run `pnpm merge-catalog`
2. Run `pnpm build`
3. Run `pnpm test:e2e:headless` to run all tests or `pnpm test:e2e` to run the tests via a GUI
4. Assert that all the tests pass
> feat: sprint 6 E2E tests 

- src/pages/CatalogueItemPage.tsx
The font color for the hero banner in the catalogue item page was not explicitly defined which makes the website default to your system defaults i.e. black text for light mode and white text for dark mode.
Add a numbered list of steps to make in order to verify that the feature is working. Ideally add a video of you
running the new features you have added. You can use a capturing tool like [ShareX](https://getsharex.com)
1. Set your system to light mode for windows 10 users, you  can search `dark mode` in the start menu search bar and change system color mode in this panel
2. Go to home page and click on a featured dataset
3. Assert that the text color for the hero banner is white
4. Repeat for a dark mode system
> fix: add catalogue item hero text color

- .github/workflows/deploy.yml
- .github/workflows/validate.yml
- chore: update gh actions
- enable manual workflow trigger of catalog item validation and deploy actions so they can be triggered via the gh actions web ui.
- update the deploy and validate gh actions.
0. Go to [deploy](https://github.com/thinkingmachines/unicef-ai4d-research-bank/actions/workflows/deploy.yml) and [validate](https://github.com/thinkingmachines/unicef-ai4d-research-bank/actions/workflows/validate.yml) actions screen
1. There should be a `Run workflow` button to allow the manual triggering of the workflow
2. Click on `Run workflow` button to trigger the workflow manually
> chore:Add manual triggering of github actions

- .github/workflows/test.yml
- cypress/e2e/catalog-item.spec.ts
- cypress/e2e/catalog-page.spec.ts
- cypress/e2e/featured-dataset.spec.ts
- cypress/e2e/filter.spec.ts
- cypress/e2e/index.spec.ts
- cypress/e2e/landing-page.spec.ts
- cypress/e2e/searchbox.spec.ts
- package.json
- public/api/data/fixtures/catalog.json
- public/api/data/fixtures/featured.json
- src/api/index.ts
Updates automated testing and tests to use a fixtures file instead of live `catalog.json` files. This should make writing tests easier and more consistent.
Future suggestions: Once more versions of the fixtures file gets uploaded, you will want the create a subfolder in the fixtures directory to track the version history of old fixtures files
Add a summary of the things that were changed
- n/a
> chore: add fixtures

- src/components/Footer.tsx
- src/components/Header.tsx
- src/pages/CatalogueItemPage.tsx
- src/pages/CataloguePage.tsx
- src/pages/ContributionPage.tsx
This PR fixes a bunch of errors related to bad margins, and phantom backgrounds appearing in mobile sized screens
https://github.com/thinkingmachines/unicef-ai4d-research-bank/assets/122899250/b21e6fb9-1f15-4ea2-b904-424defba6439
1. Assert that the the header and footer are responsive
2. Assert that the catalogue search page is responsive
3. Assert that the catalogue item page is responsive
4. Assert that the contribution page is responsive
5. Assert that the tables in the contribution page render zebra striped color styling
> fix: update mobile responsiveness, contribution page updates

- catalog/airquality-thailand-model.yml
- fix: update air quality item links with failing 403 errors during validation/merging
> fix:Update air quality links with failing 403 errors

- .github/workflows/deploy.yml
- .github/workflows/validate.yml
- fix:  deploy gh action 
- chore: remove duplicate validation step on merge since deploy also validates
Add a echo if catalog items are updated or not so exit code for step to check for catalog changes (and committing them) is zero so that its not considered an error
> fix:Update deploy to avoid erroring out on no catalog item updates

- .github/workflows/deploy.yml
- scripts/commit-catalog.sh
- fix: update deploy action to avoid repeated triggering
- move logic to scripts/commit-catalog.sh
- add ignore paths for generated files
> Update deploy action to avoid repeated triggering

- src/components/CatalogueItemData.tsx
Download links are reverted back to simple `copy link` instead of using links prefixed with `unicef.org`. Reverted due to pushback of citations user story
Add a numbered list of steps to make in order to verify that the feature is working. Ideally add a video of you
running the new features you have added. You can use a capturing tool like [ShareX](https://getsharex.com)
1. Go to `catalogue` -> click on a result -> click data tab
2. Assert that both the training datasets and results datasets now have the old `COPY LINK` buttons for CSV and GEOJSON files
> fix: revert data download links

- catalog/philippine-healthsites.yml
Updated to use google drive links because the original links redirect to another link which expires and complicates things.
> update links to use google drive

- src/pages/LandingPage.tsx
Logo is stretched in firefox browser
Fix: handling of `width-auto` is different across browsers, instead set height and width explicitly
https://github.com/thinkingmachines/unicef-ai4d-research-bank/assets/122899250/b867a28c-3aed-442a-ba1e-e5da0fc2ce14
Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
> fix stretch
